#if os(macOS)
import XCTest
@testable import OndeCore

/// Small independent ZIP fixtures cover metadata overrides and actual inflation.
/// They contain inert bytes only; no archive in this suite is ever extracted.
final class UpdateArchiveHardeningTests: XCTestCase {
    func testAcceptsReleaseZIPFeatures() throws {
        let fixtures: [(String, String)] = [
            ("Stored payload", "UEsDBBQAAAAAAAAAAACPKKQfBAAAAAQAAAAWAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdHNhZmVQSwECFAMUAAAAAAAAAAAAjyikHwQAAAAEAAAAFgAAAAAAAAAAAAAApIEAAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdFBLBQYAAAAAAQABAEQAAAA4AAAAAAA="),
            ("Raw DEFLATE payload", "UEsDBBQAAAAIAAAAAAAXOC2AIwAAAHAXAAAWAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdO3EIREAAAgEsCrEoQju7+jvCIHdxHqSrbZt27Zt27Zt248PUEsBAhQDFAAAAAgAAAAAABc4LYAjAAAAcBcAABYAAAAAAAAAAAAAAKSBAAAAAE9uZGUuYXBwL0NvbnRlbnRzL3Rlc3RQSwUGAAAAAAEAAQBEAAAAVwAAAAAA"),
            ("Data descriptor", "UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAWAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdO3EIREAAAgEsCrEoQju7+jvCIHdxHqSrbZt27Zt27Zt248PUEsHCBc4LYAjAAAAcBcAAFBLAQIUAxQACAAIAAAAAAAXOC2AIwAAAHAXAAAWAAAAAAAAAAAAAACkgQAAAABPbmRlLmFwcC9Db250ZW50cy90ZXN0UEsFBgAAAAABAAEARAAAAGcAAAAAAA=="),
            ("Identical Unicode name", "UEsDBBQAAAAAAAAAAACPKKQfBAAAAAQAAAAWAB8AT25kZS5hcHAvQ29udGVudHMvdGVzdHVwGwABYwM5k09uZGUuYXBwL0NvbnRlbnRzL3Rlc3RzYWZlUEsBAhQDFAAAAAAAAAAAAI8opB8EAAAABAAAABYAHwAAAAAAAAAAAKSBAAAAAE9uZGUuYXBwL0NvbnRlbnRzL3Rlc3R1cBsAAWMDOZNPbmRlLmFwcC9Db250ZW50cy90ZXN0UEsFBgAAAAABAAEAYwAAAFcAAAAAAA=="),
        ]
        for (name, encoded) in fixtures {
            let bytes = try XCTUnwrap(Data(base64Encoded: encoded))
            XCTAssertNoThrow(try UpdateArchiveValidation.validate(bytes), name)
        }
    }
    func testRejectsMetadataOverridesAndDishonestPayloads() throws {
        let fixtures: [(String, String)] = [
            ("Unicode path override", "UEsDBBQAAAAAAAAAAACPKKQfBAAAAAQAAAAWABYAT25kZS5hcHAvQ29udGVudHMvdGVzdHVwEgABYwM5ky4uLy4uL291dHNpZGVzYWZlUEsBAhQDFAAAAAAAAAAAAI8opB8EAAAABAAAABYAFgAAAAAAAAAAAKSBAAAAAE9uZGUuYXBwL0NvbnRlbnRzL3Rlc3R1cBIAAWMDOZMuLi8uLi9vdXRzaWRlUEsFBgAAAAABAAEAWgAAAE4AAAAAAA=="),
            ("Local Unicode path override", "UEsDBBQAAAAAAAAAAACPKKQfBAAAAAQAAAAWABUAT25kZS5hcHAvQ29udGVudHMvdGVzdHVwEQABYwM5ky90bXAvb3V0c2lkZXNhZmVQSwECFAMUAAAAAAAAAAAAjyikHwQAAAAEAAAAFgAAAAAAAAAAAAAApIEAAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdFBLBQYAAAAAAQABAEQAAABNAAAAAAA="),
            ("ASi UNIX link metadata", "UEsDBBQAAAAAAAAAAACPKKQfBAAAAAQAAAAWAAgAT25kZS5hcHAvQ29udGVudHMvdGVzdG51BABsaW5rc2FmZVBLAQIUAxQAAAAAAAAAAACPKKQfBAAAAAQAAAAWAAgAAAAAAAAAAACkgQAAAABPbmRlLmFwcC9Db250ZW50cy90ZXN0bnUEAGxpbmtQSwUGAAAAAAEAAQBMAAAAQAAAAAAA"),
            ("Unexpected ZIP64 metadata", "UEsDBBQAAAAAAAAAAACPKKQfBAAAAAQAAAAWABQAT25kZS5hcHAvQ29udGVudHMvdGVzdAEAEAAAAAAAAAAAAAAAAAAAAAAAc2FmZVBLAQIUAxQAAAAAAAAAAACPKKQfBAAAAAQAAAAWABQAAAAAAAAAAACkgQAAAABPbmRlLmFwcC9Db250ZW50cy90ZXN0AQAQAAAAAAAAAAAAAAAAAAAAAABQSwUGAAAAAAEAAQBYAAAATAAAAAAA"),
            ("False uncompressed size", "UEsDBBQAAAAIAAAAAADRauus1AAAAAEAAAAWAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdO3BMQEAAADCoGzrX8oM/kABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK8BUEsBAhQDFAAAAAgAAAAAANFq66zUAAAAAQAAABYAAAAAAAAAAAAAAKSBAAAAAE9uZGUuYXBwL0NvbnRlbnRzL3Rlc3RQSwUGAAAAAAEAAQBEAAAACAEAAAAA"),
            ("Truncated DEFLATE stream", "UEsDBBQAAAAIAAAAAADRauus0wAAAEANAwAWAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdO3BMQEAAADCoGzrX8oM/kABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK9QSwECFAMUAAAACAAAAAAA0WrrrNMAAABADQMAFgAAAAAAAAAAAAAApIEAAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdFBLBQYAAAAAAQABAEQAAAAHAQAAAAA="),
            ("Mismatched data descriptor", "UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAWAAAAT25kZS5hcHAvQ29udGVudHMvdGVzdPNIzcnJBwBQSwcIgonR9wgAAAAFAAAAUEsBAhQDFAAIAAgAAAAAAIKJ0fcHAAAABQAAABYAAAAAAAAAAAAAAKSBAAAAAE9uZGUuYXBwL0NvbnRlbnRzL3Rlc3RQSwUGAAAAAAEAAQBEAAAASwAAAAAA"),
            ("Filesystem case-fold collision", "UEsDBBQAAAgAAOmKNV2LntnTAQAAAAEAAAALAAAAT25kZS5hcHAvw59BUEsDBBQAAAAAAOmKNV0xz9BKAQAAAAEAAAALAAAAT25kZS5hcHAvc3NCUEsBAhQDFAAACAAA6Yo1XYue2dMBAAAAAQAAAAsAAAAAAAAAAAAAAIABAAAAAE9uZGUuYXBwL8OfUEsBAhQDFAAAAAAA6Yo1XTHP0EoBAAAAAQAAAAsAAAAAAAAAAAAAAIABKgAAAE9uZGUuYXBwL3NzUEsFBgAAAAACAAIAcgAAAFQAAAAAAA=="),
        ]
        for (name, encoded) in fixtures {
            let bytes = try XCTUnwrap(Data(base64Encoded: encoded))
            XCTAssertThrowsError(try UpdateArchiveValidation.validate(bytes), name)
        }
    }
}
#endif
